apiVersion: v1
kind: PersistentVolume
metadata:
  name: append-only-store-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp
