apiVersion: v1
kind: Service
metadata:
  name: append-only-store-service
spec:
  type: NodePort
  selector:
    app: append-only-store
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30008
